### ISSUE TITLE
ITypeDefinition get additionalProperties value

### ISSUE THREAD

**Issue by domarmstrong** [raml-org/raml-typesystem#93]
```
types:
  Foo:
    type: object
    additionalProperties: false
    properties:
      foo: string
```

For example I have Foo as a runtimeType, but cant seem to get the value of additionalProperties.

```
type.facets() -> []
type.allFacets() -> []
type.allFixedFacets() -> {}
```

Any suggestions?
